### ISSUE TITLE
any efforts to use ios camera?

### ISSUE THREAD

**Issue by 8secz-johndpope** [k0staa/real-time-example-of-first-order-motion-model-for-image-animation#1]
I understand you can use OBNinja - obs virtual camera.
https://github.com/alievk/avatarify-python/issues/339

**Comment by k0staa** [comment]
I have no idea and no plans to try do something like this. If you want to use output as fake camera input you should be able to do this using pyfakewebcam as described [here](https://stackoverflow.com/questions/21446292/using-opencv-output-as-webcam).
Maybe I will try implement something like that :smile: in this repo but also not soon.
