### ISSUE TITLE
Video file instead of live video stream

### ISSUE THREAD

**Issue by BOXNYC** [k0staa/real-time-example-of-first-order-motion-model-for-image-animation#3]
Is it possible to run this using an .mp4 instead of the live camera? I'm trying to install this on a remote Linux server. Thanks!

**Comment by k0staa** [comment]
Yes, why not. By default this code should run without turning on camera - just remove the code related to opening camera source and then it will take `VIDEO_RECORDING_CROPED_TEST` file as source.

**Comment by BOXNYC** [comment]
Thanks, I'll look through your code for the webcam opener, I'm not a py developer but hopefully I can find it and comment it out.

Is VIDEO_RECORDING_CROPED_TEST an env variable? A --param? I don't see it in your code. 

Also, being that I'm building this on a server, what should I do about the $DISPLAY variable?

Thanks!
