### ISSUE TITLE
Error in the build command

### ISSUE THREAD

**Issue by JaMePa** [k0staa/real-time-example-of-first-order-motion-model-for-image-animation#4]
Hi folk, 
see that:
![image](https://github.com/k0staa/real-time-example-of-first-order-motion-model-for-image-animation/assets/45750200/4949274d-fc08-4fd2-bc5e-a079ff404179)

**Comment by k0staa** [comment]
Thanks for flagging this problem @JaMePa .
I will work on this issue. I already fixed building process and image generation however, there are still issues with OpenCV that I will be working on.

Workaround for now:
1. Please use https://github.com/k0staa/real-time-example-of-first-order-motion-model-for-image-animation/tree/bug/Fixing_build_issues_plus_upgrade branch.
2. Skip sections which I marked as "(NOT WORKING AT THE MOMMENT)"
3. Currently you can generate an image animation using my video (`temp/test_video_cropped.avi`). You can also record your own video using diffent applicaiton and replace my video (use same frame size and format)

I will solve the remaining problems soon (probably next weekend)

**Comment by k0staa** [comment]
All fixed now -> https://github.com/k0staa/real-time-example-of-first-order-motion-model-for-image-animation/pull/6
